#include <stdio.h>
#include <stddef.h>

typedef unsigned short UINT16;
typedef unsigned long UINT64;
#include "State.h"

#define GEN(name, field) printf("#define STATE_" #name " 0x%04lx\n", offsetof(struct cpu_state, field))
int main() {
  printf("/* auto-generated by GenStateOffsets.c */\n\n");
  GEN(MAGIC, magic);
  GEN(VERSION, version);
  GEN(REGS_R15, regs.r15);
  GEN(REGS_R14, regs.r14);
  GEN(REGS_R13, regs.r13);
  GEN(REGS_R12, regs.r12);
  GEN(REGS_BP, regs.bp);
  GEN(REGS_BX, regs.bx);
  GEN(REGS_R11, regs.r11);
  GEN(REGS_R10, regs.r10);
  GEN(REGS_R9, regs.r9);
  GEN(REGS_R8, regs.r8);
  GEN(REGS_AX, regs.ax);
  GEN(REGS_CX, regs.cx);
  GEN(REGS_DX, regs.dx);
  GEN(REGS_SI, regs.si);
  GEN(REGS_DI, regs.di);
  GEN(REGS_ORIG_AX, regs.orig_ax);
  GEN(REGS_IP, regs.ip);
  GEN(REGS_CS, regs.cs);
  GEN(REGS_FLAGS, regs.flags);
  GEN(REGS_SP, regs.sp);
  GEN(REGS_SS, regs.ss);
  GEN(DS, ds);
  GEN(ES, es);
  GEN(FS, fs);
  GEN(GS, gs);
  GEN(TR, tr);
  GEN(FS_BASE, fs_base);
  GEN(GS_BASE, gs_base);
  GEN(KERNELGS_BASE, kernelgs_base);
  GEN(CR0, cr0);
  GEN(CR2, cr2);
  GEN(CR3, cr3);
  GEN(CR4, cr4);
  GEN(EFER, efer);
  GEN(SYSENTER_CS, sysenter_cs);
  GEN(SYSENTER_ESP, sysenter_esp);
  GEN(SYSENTER_EIP, sysenter_eip);
  GEN(STAR, star);
  GEN(LSTAR, lstar);
  GEN(CSTAR, cstar);
  GEN(FMASK, fmask);
  GEN(TSC_AUX, tsc_aux);
  GEN(GDT_DESC, gdt_desc);
  GEN(IDT, idt);
  GEN(END_MAGIC, end_magic);
  printf("\n");
  printf("#define SIZEOF_CPU_STATE 0x%04lx\n", sizeof(struct cpu_state));
  return 0;
}
